### ISSUE TITLE
MixPanel API error: Expired request

### ISSUE THREAD

**Issue by durch** [stpe/mixpanel-engage-query#2]
Getting expired request, how and where is 'expire' defined?

**Comment by godspeedelbow** [comment]
I had this issue just now as well on Mac OS X: my clock seems to be slower than real time. 
Click on Clock on menu bar "Open Date & Time Preferences..." and then your clock gets synced to Internet Time (it should do that the whole time, but for some reason, it doesn't). 

After that, no error.

**Comment by stpe** [comment]
Thanks for the tip @godspeedelbow!

Maybe worth to add the expire variable as a parameter in case of situations like this (and if there is a need to construct URLs with another expire period using the `--url` parameter), hmm...

**Comment by stpe** [comment]
For anyone finding this issue. Another quick way to update the internal clock is, using Terminal:

`ntpdate -s pool.ntp.org`
