### ISSUE TITLE
Split on comma instead on space for properties (p and r)

### ISSUE THREAD

**Issue by jeromecance** [stpe/mixpanel-engage-query#4]
A little suggestion : 
I have a lot of properties that contain spaces into their name. I can't use them with p and r parameters because the split is done on space. If the split is done on comma, I could use property name with space. 
Or, if we split on space, add the possibility to use quote for properties with spaces.

By the way, this is an excellent script ;) thank you !

**Comment by stpe** [comment]
Thanks @jeromecance! I will have a look at it!

**Comment by stpe** [comment]
Change merged #5
