### ISSUE TITLE
Remove secrets from repo 

### ISSUE THREAD

**Issue by sandeep89** [stpe/mixpanel-engage-query#7]
You README and .env files have all mixpanel api key an secrets 
degoo_MIXPANEL_API_KEY=f89785f7a01dbe7662099c6ea04b88b4
degoo_MIXPANEL_API_SECRET=a69aa385a71f8de23fdff5ed55cabb26
MIXPANEL_API_KEY=55dcba882ca5ce49e8306aae1c8399b6
MIXPANEL_API_SECRET=4f8a8f7f8a22c3357932221136132b0c

Remove them before someone misuses :)

**Comment by stpe** [comment]
Thanks for your concern. 👍 They’re just made up examples - not real keys.
